#include "StreamingPowerMergedConnectionComponentContainer.h"

FStreamingPowerMergedConnectionComponent UStreamingPowerMergedConnectionComponentContainer::GetStreamingPowerMergedConnectionComponent(FAstroDatumRef StreamingPowerMergedConnectionComponentRef, bool& bOutSuccess) {
    return FStreamingPowerMergedConnectionComponent{};
}

FStreamingPowerMergedConnectionComponent UStreamingPowerMergedConnectionComponentContainer::FindStreamingPowerMergedConnectionComponent(FAstroDatumRef EntityRef, bool& bOutSuccess) {
    return FStreamingPowerMergedConnectionComponent{};
}

UStreamingPowerMergedConnectionComponentContainer::UStreamingPowerMergedConnectionComponentContainer() {
}

