#include "StreamingPowerDirectionalConnectionComponentContainer.h"

FStreamingPowerDirectionalConnectionComponent UStreamingPowerDirectionalConnectionComponentContainer::GetStreamingPowerConnectionComponent(FAstroDatumRef StreamingPowerConnectionComponentRef, bool& bOutSuccess) {
    return FStreamingPowerDirectionalConnectionComponent{};
}

FStreamingPowerDirectionalConnectionComponent UStreamingPowerDirectionalConnectionComponentContainer::FindStreamingPowerConnectionComponent(FAstroDatumRef EntityRef, bool& bOutSuccess) {
    return FStreamingPowerDirectionalConnectionComponent{};
}

UStreamingPowerDirectionalConnectionComponentContainer::UStreamingPowerDirectionalConnectionComponentContainer() {
}

