#include "StreamingPowerVampireConnectionComponentContainer.h"

FStreamingPowerVampireConnectionComponent UStreamingPowerVampireConnectionComponentContainer::GetStreamingPowerVampireConnectionComponent(FAstroDatumRef StreamingPowerVampireConnectionComponentRef, bool& bOutSuccess) {
    return FStreamingPowerVampireConnectionComponent{};
}

FStreamingPowerVampireConnectionComponent UStreamingPowerVampireConnectionComponentContainer::FindStreamingPowerVampireConnectionComponent(FAstroDatumRef EntityRef, bool& bOutSuccess) {
    return FStreamingPowerVampireConnectionComponent{};
}

UStreamingPowerVampireConnectionComponentContainer::UStreamingPowerVampireConnectionComponentContainer() {
}

