#pragma once
#include "CoreMinimal.h"
#include "EAstroAchievementKeys.generated.h"

UENUM(BlueprintType)
enum class EAstroAchievementKeys : uint8 {
    TutorialDone,
    HazardUprooted,
    ResearchChamber,
    InstantResearch,
    SoilExtract,
    CatalyzeComponent,
    CollectGas,
    BuildRover,
    UseShredder,
    TradePlatform,
    HardTerrain,
    GoMantle,
    PlantSeed,
    ChangeSuit,
    PuzzleSolve,
    EveryComponent,
    EveryGas,
    ScrapX,
    EverySeed,
    EveryRaw,
    EverySmelt,
    EverySchematic,
    BytesGain,
    BytesConcurrent,
    ChamberAll,
    FindChamber,
    SolveChamber,
    FindEngine,
    SolveTerranEngine,
    SolveBarrenEngine,
    SolveAridEngine,
    SolveExoticEngine,
    SolveExomoonEngine,
    SolveTundraEngine,
    SolveRadiatedEngine,
    SolveAllEngines,
    LeaveTerran,
    LandMoon,
    LandArid,
    LandExotic,
    LandExoMoon,
    LandRadiated,
    LandTundra,
    FastTravel,
    BeatGame,
    SlideTime,
    RoverAirtime,
    PlanetDance,
    BackpackFirework,
    MPSession,
    GuestResearch,
    MPCore,
    MPTime,
    CoOpShuttle,
    AllAchievements,
    WandererFirstProbe,
    WandererAllProbes,
    COUNT,
};

