#pragma once
#include "CoreMinimal.h"
#include "EAstroInputBindingNameMappings.generated.h"

UENUM(BlueprintType)
enum class EAstroInputBindingNameMappings : uint8 {
    Invalid,
    Use,
    Catalog,
    Backpack,
    TerrainTool,
    Confirm,
    Cancel,
    ContextLeft,
    ContextRight,
    Jump,
    PlaceTether,
    MouseWheelUp,
    MouseWheelDown,
    QuickSelectModifier,
    UseModifier,
    Emote1,
    Emote2,
    Emote3,
    Emote4,
    NavigateLeft,
    NavigateRight,
    NavigateUp,
    NavigateDown,
    CategoryScrollLeft,
    CategoryScrollRight,
    ToggleEscapeMenu,
    ToggleDebugMenu,
    TeleportToCursor,
    FOVUp,
    FOVDown,
    DeleteActiveMultiToolItem,
    DuplicateActiveMultiToolItem,
    ChangeDeformBrushSizeModifier,
    ChangeDeformBrushStrengthModifier,
    IncrementBrushSizeController,
    DecrementBrushSizeController,
    IncrementBrushIntensityController,
    DecrementBrushIntensityController,
    AirControlRollYawModifier,
    EmoteWheel,
    ActionWheel,
    LeftTriggerToggle,
    MotionForwardBack,
    MotionLeftRight,
    CameraTilt,
    CameraPan,
    CameraPedestal,
    SelectionRotate,
    ArrowRight,
    ArrowForward,
    LeftTrigger,
    RightTrigger,
    Focus,
    Sprint,
    DeformAdd,
    DeformFlatten,
    DeformSmooth,
    VehicleThrottle,
    ToggleDeformToolMenu,
    CameraModeModifier,
};

